### ISSUE TITLE
Custom grammar not running

### ISSUE THREAD

**Issue by Hamza-101** [tdishant/ll1-parser#1]
E -> T | EP
EP -> + | T | EP
EP -> @
T ->  F | id
TP -> * | F | TP
TP -> @
F -> (E) 
F -> id

Error:
![image](https://user-images.githubusercontent.com/45544623/152052933-b8d5e8a0-d91f-4065-a955-c43c90529cfa.png)

**Comment by tdishant** [comment]
> 

Hey Thanks for showing interest in the code

You will have to slightly modify your grammar as follows:

S -> T | E
E -> + | T | E
E -> ε
T -> F | id
P -> * | F | P
P -> ε
F -> (E)
F -> id

Even though the code works fine in most of the cases, it might not be fully robust and may not be able to cover certain grammars. Although you are more than welcome to modify the code and make it better.

Hope this helps.

**Comment by Hamza-101** [comment]
Error:
![image](https://user-images.githubusercontent.com/45544623/152140816-a19aad21-afa0-4307-b946-0e76b7092376.png)

**Comment by Hamza-101** [comment]
> > 
> 
> Hey Thanks for showing interest in the code
> 
> You will have to slightly modify your grammar as follows:
> 
> S -> T | E E -> + | T | E E -> ε T -> F | id P -> * | F | P P -> ε F -> (E) F -> id
> 
> Even though the code works fine in most of the cases, it might not be fully robust and may not be able to cover certain grammars. Although you are more than welcome to modify the code and make it better.
> 
> Hope this helps.



> Error: ![image](https://user-images.githubusercontent.com/45544623/152140816-a19aad21-afa0-4307-b946-0e76b7092376.png)

Had to use @ sign instead of epsilon.

**Comment by Hamza-101** [comment]
Replaced epsilon with @. Shouldn't this work?
![Uploading image.png…]()
